Configuring for pure-python-without-pypy
zopefoundation/z3c.layer.pagelet pull request #4
Opened 2020-05-13 12:52 UTC by sallner

2020-05-13 12:58 UTC, dataflake requested changes
Don't forget to add a change log entry

2020-05-13 13:00 UTC, jamadden reviewed
> The drop of coverage is a result of stopping the coverage collection with Python 2.7.

Also, the .coveragerc (at least its settings) needs restored to fix the drop in coverage. There are "#pragma" comments that seem to be ignored now.

2020-05-13 13:01 UTC, jamadden commented
> The drop of coverage is a result of stopping the coverage collection with Python 2.7.

Then why do that? Standardization on a template doesn't make sense if it breaks things.

2020-05-13 13:04 UTC, dataflake commented
In a discussion that pre-dates this sprint I had asked Michael to not use `.coveragerc` anymore and put all those settings into `setup.cfg` so we have one central place for those configurations. That's where the automated removal comes from. Whoever runs the updater must make sure anything that used to be in `.coveragerc` is transcribed into `setup.cfg`.

2020-05-13 13:04 UTC, sallner commented
I would argue, that these changes are only infrastructural and that they do not need a changelog entry.

2020-05-13 13:05 UTC, dataflake commented
> I would argue, that these changes are only infrastructural and that they do not need a changelog entry.

OK, I agree.

2020-05-13 13:05 UTC, dataflake approved these changes

2020-05-13 13:08 UTC, sallner commented
> > The drop of coverage is a result of stopping the coverage collection with Python 2.7.
> 
> Then why do that? Standardization on a template doesn't make sense if it breaks things.

It was actually only a result of the `.coveragerc`, which `exlcude_patterns` is added now to the template.

2020-05-13 13:41 UTC, merged

2020-05-13 16:24 UTC, mgedmin commented on tox.ini
> +    coverage report -m
Mildly worried that removal of the 98% threshold will now allow the coverage to backslide.

(Unless we have coveralls.io configured to track coverage and post commit statuses?)

2020-05-13 16:25 UTC, mgedmin commented on tox.ini
> +source = src
`.coveragerc` had `source = z3c.layer.pagelet`, which in theory would allow us to track coverage even without `usedevelop = true`.

2020-05-13 16:27 UTC, mgedmin commented on tox.ini
> +    coverage report -m
Yeah, https://coveralls.io/github/zopefoundation/z3 shows

> COVERAGE THRESHOLD FOR FAILURE  [  98.5%]
> COVERAGE DECREASE THRESHOLD FOR FAILURE [   0.2%]

which is, wow, I usually set the decrease threshold to 1%.

2020-05-13 16:28 UTC, mgedmin commented
> The drop of coverage is a result of stopping the coverage collection with Python 2.7.

I like https://pypi.org/project/coverage-python-version/ for this kind of situation.

> It was actually only a result of the .coveragerc, which exlcude_patterns is added now to the template.

... but apparently it's not necessary here.

2020-05-14 06:44 UTC, sallner commented
We have added `coverage-python-version` to the template already for further use.